version: '3.8'

services:
  booking-hotel-service:
    container_name: booking-hotel-service
    image: binhtt13122000/booking-mvp-hrs
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_REGION=${AWS_DEFAULT_REGION}
volumes:
  db-booking-data: